### PR TITLE
Mate/comments

### PR DESCRIPTION
**Pull request by matereyes00**

### CODE REVIEW

**Comment by matereyes00** [comment]
Re. the DE comment on linking the article on "(1972-1984)", naka link naman siya but the website isnt responding? I checked the link and it works naman but its only when we href it where it doesn't cooperate anymore

**Comment by theguidon** [comment]
image

- that "couldnt click" problem happens cos your elements are all messed up
- grid and flex exists so this could have been easily avoided but i just don't know what you did with the css

- [ ] fix: just add `pointer-events: none` to the highlighted element

---

image

- [ ] no edits??? make logo same size as the one in landing

---

image

- [ ] no edits??? title case might just be using "Photos by ..." where first letter is capitalized, it's just editing the html :)

**Comment by theguidon** [comment]
image

- [ ] title case also applies to names

**Comment by theguidon** [comment]
or actually no, merging now

**Pull request merged**
