### PR TITLE
Addressed comment: suggest to use max-width: 550px or 768px for break…

### PR DESCRIPTION
**Pull request by matereyes00**

### CODE REVIEW

**Comment by theguidon** [comment]
hi im not sure which tasks ito but can you merge it also with the overlay task para di multiple branches?

**Comment by theguidon** [comment]
i've tested and this works for mobile overlay btw

```
width 100%
height 100%
overflow-y scroll
border-radius: 0
```

**Comment by matereyes00** [comment]
Oh! This is for article 1 [desktop] do I merge it pa rin with overlay-mobile or no more na?

**Comment by theguidon** [comment]
yes please merge this branch with overlay mobile

better yet, merge all 3 branches HAHA

**Comment by matereyes00** [comment]
Sige will do!

**Pull request closed without merging**
