### PR TITLE
fixed comments

### PR DESCRIPTION
**Pull request by PinkkSnowman**

### CODE REVIEW

**Comment by theguidon** [comment]
image

- [ ] follow the line breaks from the article. use double `<br />`

---

image

- [ ] i dont see any changes here

---
image

- [ ] rigged..? something got cut off here

**Comment by theguidon** [comment]
image

- [ ] please check mina's comments :)

**Comment by PinkkSnowman** [comment]
the first one already had changes tho.. I thought you still wanted it bigger

**Comment by PinkkSnowman** [comment]
image
image
This is before and after the first change

**Comment by PinkkSnowman** [comment]
ah wait i now understand the problem i think

**Comment by PinkkSnowman** [comment]
image
this is how it looks now!

**Comment by theguidon** [comment]
BETTER

**Pull request merged**
