### PR TITLE
article 3 mobile

### PR DESCRIPTION
**Pull request by PinkkSnowman**

### CODE REVIEW

**Comment by theguidon** [comment]
image
- [ ] fix, should be 100% width pa rin (but maybe fixed height!). `object-fit: cover` can help

---

image
- [ ] in mobile, dapat nasa same column na siya not flushed to right

---

CLEANNNNN

**Comment by theguidon** [comment]
image
image
image

- [ ] set images to: `width: 100%`, `margin-left: auto`, `margin-right: auto`, `max-width: 400px` for mobile

**Comment by theguidon** [comment]
CLOSEDDD MERGING

**Comment by theguidon** [comment]
article 3 closed!

- [ ] article 2 desktop
- [ ] article 2 mobile

**Comment by theguidon** [comment]
- [ ] icons should link to subheadings
- [ ] g to start on mobile

**Comment by theguidon** [comment]
- [ ] g to start on mobile

**Comment by theguidon** [comment]
image
image


- [ ] add `align-items: center` sa main container grid
- [ ] add `column-gap` and `row-gap` sa main container grid

---

image

- [ ] these should all be divs with these classes (e.g., a `main container` actually means `div.main-container` bruh), don't copy the stuff i sent, they're just pseudocode

---

image

- [ ] can you only put all content in a single `.overlay-article`
- look at the difference between html of the first article with the second and third, there's only one `.overlay-article` per overlay

**Comment by theguidon** [comment]
image
image

- [ ] what happened here, pls fix
- i think u forgot to update ur css

---

image

- [ ] do the same with article 3
- [ ] make sure the css doesn't break :)

**Comment by PinkkSnowman** [comment]
ah i committed the wrong file lol

**Comment by theguidon** [comment]
all g na for me hehe merging!

**Pull request merged**
