### PR TITLE
About Page

### PR DESCRIPTION
**Pull request by PinkkSnowman**

### CODE REVIEW

**Comment by PinkkSnowman** [comment]
can you check if the margins are correct now I used the box dimension in figma 
thank you!!

**Comment by theguidon** [comment]
image
image

- nope still wrong
- all margins incorrect

---

- [ ] fix margins
- [ ] **Photos by** text

---

image

- [ ] remove this `height` in the css

**Comment by PinkkSnowman** [comment]
should the text be flush on the bottom of the screen like this?

image

**Comment by theguidon** [comment]
look at the left margin

**Comment by PinkkSnowman** [comment]
oh okok

**Comment by PinkkSnowman** [comment]
Is this better?
image

**Comment by theguidon** [comment]
yepp!

- [ ] in `about`, pls change `height: 100vh` to `min-height: 100vh` (revert it back!)
- [ ] add gradient na lang for `aboutblock` - transparent (top) to black (bottom)

**Comment by theguidon** [comment]
image

- [ ] set `margin-left: auto`
- [ ] change padding from `5%`. how did you even get this? **the values should be on figma already**. if you actually checked, you'd see it's actually 91.67
- [ ] test different values for the gradient. try `0% transparent, 75% black` or other values and comment which one looks good to you

---
image

**Comment by PinkkSnowman** [comment]
oh sorry i sorta just eyeballed it because i didnt know how to see those values on figma

**Comment by theguidon** [comment]
CLOSED!!! THANK YOUUUU

**Pull request merged**
